- name: Clone my git repositories
  git:
    repo: "https://github.com/joereynolds/{{ item }}"
    dest: "/home/joe/code/me/{{ item }}"
  with_items:
      - joereynolds/life
      - joereynolds/joereynolds.github.io
