- name: Clone git repositories
  git:
    repo: "https://github.com/{{ item }}"
    dest: "/home/joe/code/me/{{ item }}"
  with_items:
      - joereynolds/configs
      - joereynolds/boganspunkrock
      - joereynolds/life
      - joereynolds/programming-dump
      - joereynolds/util.joereynoldsaudio
      - joereynolds/joereynolds.github.io
      - neovim/neovim
      - universal-ctags/ctags
