abbr setene sentence
abbr sentene sentence
abbr sentnece sentence
abbr recive receive
abbr teh the
abbr aginst against
abbr yor your
abbr agian again
abbr cahcing caching
abbr cahching caching
abbr detials details
abbr detaisl details
abbr validatino validation
