jack.rules = [
    {
        matches = [
            {
                client.name = "REAPER"
            }
        ]
        actions = {
            update-props = {
                node.latency = 128/48000
                node.force-quantum = 128
            }
        }
    }
]
