- name: Download dbeaver
  get_url:
    url: https://github.com/dbeaver/dbeaver/releases/download/6.0.3/dbeaver-ce_6.0.3_amd64.deb
    dest: /tmp/dbeaver.deb

- name: Install deb packages
  apt: deb=/tmp/dbeaver.deb
  become: true

- name: Install apt repositories
  apt:
    update_cache: yes
    name: "{{ item }}"
  become: true
  with_items:
      - automake
      - cmake
      - composer
      - curl
      - google-chrome-stable
      - exuberant-ctags
      - git
      - i3
      - libtool
      - libtool-bin
      - python-dev
      - rake
      - ppa-purge
      - python-pip
      - python3-pip
      - thunar
