# - name: Download debian packages
#   get_url:
#     url: "{{ item.url }}"
#     dest: "{{ item.dest }}"
#   with_items:
#     - { url: "https://github.com/dbeaver/dbeaver/releases/download/7.0.0/dbeaver-ce_7.0.0_amd64.deb", dest: '/tmp/dbeaver.deb' }
#     - { url: "https://github.com/sharkdp/fd/releases/download/v7.4.0/fd_7.4.0_amd64.deb", dest: "/tmp/fd.deb" }

#- name: Install debian packages
#  apt: 
#    deb: "{{ item }}"
#  become: true
#  with_items:
#    - "https://github.com/dbeaver/dbeaver/releases/download/7.2.5/dbeaver-ce_7.2.5_amd64.deb"
#    - "https://github.com/sharkdp/fd/releases/download/v8.1.1/fd_8.1.1_amd64.deb"

- name: Download Z
  get_url:
    url: https://raw.githubusercontent.com/rupa/z/master/z.sh
    dest: ~/z.sh
    mode: "0775"
