- name: Download debian packages
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  with_items:
    - { url: 'https://github.com/dbeaver/dbeaver/releases/download/6.1.5/dbeaver-ce_6.1.5_amd64.deb',    dest: '/tmp/dbeaver.deb' }
    - { url: "https://github.com/sharkdp/fd/releases/download/v7.3.0/fd_7.3.0_amd64.deb", dest: "/tmp/fd.deb" }

- name: Install debian packages
  apt: 
    deb: "{{ item }}"
  become: true
  with_items:
    - https://github.com/dbeaver/dbeaver/releases/download/6.1.5/dbeaver-ce_6.1.5_amd64.deb
    - https://github.com/sharkdp/fd/releases/download/v7.3.0/fd_7.3.0_amd64.deb

- name: Download Z
  get_url:
    url: https://raw.githubusercontent.com/rupa/z/master/z.sh
    dest: ~/z.sh
    mode: "0775"

- name: Install ripgrep
  become: true
  snap:
    name: ripgrep
    classic: yes

- name: Install spotify
  become: true
  snap:
    name: spotify

- name: Install apt repositories
  apt:
    update_cache: yes
    name: "{{ packages }}"
  become: true
  vars:
    packages:
        - automake
        - cmake
        - composer
        - curl
        - exuberant-ctags
        - fzy
        - git
        - i3
        - libtool
        - libtool-bin
        - nodejs
        - npm
        - python-dev
        - rake
        - pavucontrol
        - ppa-purge
        - python-pip
        - python3-pip
        - thunar
