- name: Download dbeaver
  get_url:
    url: https://github.com/dbeaver/dbeaver/releases/download/5.0.1/dbeaver-ce_5.0.1_amd64.deb
    dest: /tmp/dbeaver.deb

- name: Install deb packages
  apt: deb=/tmp/dbeaver.deb
  become: true

- name: Add peek repository
  apt_repository:
    repo: 'ppa:peek-developers/stable'
    state: present

- name: Install apt repositories
  apt:
    update_cache: yes
    name: "{{ item }}"
  become: true
  with_items:
      - automake
      - cmake
      - composer
      - curl
      - google-chrome-stable
      - exuberant-ctags
      - git
      - libtool
      - libtool-bin
      # - npm
      - python-dev
      - rake
      - peek
      - php7.1
      - php7.1-curl
      - php7.1-mbstring
      - php7.1-simplexml
      - ppa-purge
      - python-pip
      - python3-pip
