# - name: Download debian packages
#   get_url:
#     url: "{{ item.url }}"
#     dest: "{{ item.dest }}"
#   with_items:
#     - { url: "https://github.com/dbeaver/dbeaver/releases/download/7.0.0/dbeaver-ce_7.0.0_amd64.deb", dest: '/tmp/dbeaver.deb' }
#     - { url: "https://github.com/sharkdp/fd/releases/download/v7.4.0/fd_7.4.0_amd64.deb", dest: "/tmp/fd.deb" }
#     - { url: "https://github.com/BurntSushi/ripgrep/releases/download/12.0.1/ripgrep_12.0.1_amd64.deb", dest: "/tmp/rg.deb" }

#- name: Install debian packages
#  apt: 
#    deb: "{{ item }}"
#  become: true
#  with_items:
#    - "https://github.com/dbeaver/dbeaver/releases/download/7.2.5/dbeaver-ce_7.2.5_amd64.deb"
#    - "https://github.com/sharkdp/fd/releases/download/v8.1.1/fd_8.1.1_amd64.deb"
#    - "https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep_12.1.1_amd64.deb"

- name: Download Z
  get_url:
    url: https://raw.githubusercontent.com/rupa/z/master/z.sh
    dest: ~/z.sh
    mode: "0775"

- name: Install snap packages
  become: true
  snap:
    name: "{{ packages }}"
  vars:
    packages:
      - htop

- name: Install apt repositories
  apt:
    update_cache: yes
    name: "{{ packages }}"
  become: true
  vars:
    packages:
        # Manage i3 window layouts
        - arandr
        - automake
        - cmake
        - composer
        - curl
        - exuberant-ctags
        # fuzzy finder for vim/other things (Not available on 16.04)
        - fzy
        - git
        - i3-wm
        - i3status
        - i3lock
        - suckless-tools
        # Screenshotting
        - kde-spectacle
        - libtool
        - libtool-bin
        # Diff and mergetool
        - meld
        # Has vidir in it
        - moreutils
        - nodejs
        - npm
        - python-dev
        - rake
        - pavucontrol
        - ppa-purge
        # Music stuff
        - puredata
        # i3 compatible screen recorder
        - simplescreenrecorder
        # clipboard provider for neovim
        - xclip
        - xdotool
